### ISSUE TITLE
Simple Suggestions

### ISSUE THREAD

**Issue by geerc** [comptonb37/comptonb37.github.io#5]
First paraphraph
- In the third sentence consider rephrashing "to music from a wide variety of genres" to something like "a wide variates of music genres"

Second paragraph
- On line 5 I would consider adding a comma after "out loud"

**Comment by comptonb37** [comment]
Thanks for the feedback! I like the change to the first paragraph and have implemented it without the word "genres" because I also think it sounds better that way. Your suggestion for adding a comma after "out loud" wouldn't be syntactically correct as the rest of the sentence is not an independent clause, so I won't be implementing this change. If you could explain to me why I should add the comma, I'd love to hear it. Again, thank you for your response!
